ALTER TABLE transfer_jobs ADD COLUMN episode_start INTEGER NOT NULL DEFAULT 0;
ALTER TABLE transfer_jobs ADD COLUMN episode_end INTEGER NOT NULL DEFAULT 0;
ALTER TABLE subscriptions ADD COLUMN last_episode INTEGER NOT NULL DEFAULT 0;
